Repository jinan159/airbnb, pull requests merged in 2022-05, with the labels that each got.

#12 feat: modal portal 기능 추가
  public/index.html
  src/common/portal.ts
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
  src/components/Search/Search.tsx
Labels: FE

#15 [BE] Entity, DB 설계 완료 PR
  backend/src/main/java/codesquad/airbnb/accomodation/Accommodation.java
  backend/src/main/java/codesquad/airbnb/accomodation/Address.java
  backend/src/main/java/codesquad/airbnb/accomodation/Image.java
  backend/src/main/java/codesquad/airbnb/accomodation/Provides.java
  backend/src/main/java/codesquad/airbnb/common/Money.java
  backend/src/main/java/codesquad/airbnb/fees/FeesPolicy.java
  backend/src/main/java/codesquad/airbnb/member/Member.java
  backend/src/main/java/codesquad/airbnb/reservation/Reservation.java
  backend/src/main/java/codesquad/airbnb/reservation/Schedule.java
  backend/src/main/java/codesquad/airbnb/reservation/StartEndDate.java
  backend/src/main/java/codesquad/airbnb/wish/Wish.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/airbnb-schema.sql
Labels: BE

#16 [BE] 불필요 항목 제거
  backend/src/main/java/codesquad/airbnb/fees/FeesPolicy.java
Labels: bug, BE

#17 [FE] 캘린더 구현 중간 PR
  public/assets/images/left.svg
  public/assets/images/right.svg
  src/App.tsx
  src/common/global.ts
  src/common/portal.ts
  src/common/portal.types.ts
  src/common/styled.d.ts
  src/common/theme.ts
  src/common/util.styled.ts
  src/components/Calendar/Calendar.styled.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Calendar.types.ts
  src/components/Calendar/index.ts
  src/components/CalendarModal/CalendarModal.styled.ts
  src/components/CalendarModal/CalendarModal.tsx
  src/components/CalendarModal/CalendarModal.types.ts
  src/components/CalendarModal/index.ts
  src/components/Check/Check.styled.ts
  src/components/Check/Check.tsx
  src/components/Check/index.ts
  src/components/DateCell/DateCell.styled.ts
  src/components/DateCell/DateCell.tsx
  src/components/DateCell/DateCell.types.ts
  src/components/DateCell/index.ts
  src/components/Fare/Fare.tsx
  src/components/Fare/index.ts
  src/components/GNB/GNB.tsx
  src/components/GNB/index.ts
  src/components/Header/Header.tsx
  src/components/Header/index.ts
  src/components/Hero/Hero.styled.ts
  src/components/Hero/Hero.tsx
  src/components/Hero/Hero.types.ts
  src/components/Hero/index.ts
  src/components/InputText/InputText.styled.ts
  src/components/InputText/InputText.tsx
  src/components/InputText/InputText.types.ts
  src/components/InputText/index.ts
  src/components/Menu/Menu.styled.ts
  src/components/Menu/Menu.tsx
  src/components/Menu/Menu.types.ts
  src/components/Menu/index.ts
  src/components/Personnel/Personnel.tsx
  src/components/Personnel/index.ts
  src/components/Search/Search.tsx
  src/components/Search/index.ts
  src/constant/constant.ts
  src/constant/index.ts
  src/pages/Home/Home.tsx
  src/pages/Home/index.ts
  src/pages/Rooms/Rooms.tsx
  src/pages/Rooms/index.ts
Labels: FE

#18 숙소 가격 통계 API 추가 PR
  .github/workflows/deploy-prod-be.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/codesquad/airbnb/accomodation/AccommodationController.java
  backend/src/main/java/codesquad/airbnb/accomodation/Image.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Accommodation.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Address.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Image.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Provides.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCount.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCountStatistics.java
  backend/src/main/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepository.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsService.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AmountUnitPolicy.java
  backend/src/main/java/codesquad/airbnb/config/QueryDSLConfig.java
  backend/src/main/java/codesquad/airbnb/reservation/Reservation.java
  backend/src/test/java/codesquad/airbnb/ApiDocumentUtils.java
  backend/src/test/java/codesquad/airbnb/accomodation/AccommodationControllerTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepositoryTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsServiceTest.java
  backend/src/test/java/codesquad/airbnb/config/JasyptConfigTest.java
  backend/src/test/resources/application.properties
  backend/src/test/resources/sql/accommodation-statistics.sql
Labels: BE

#19 1차 배포 PR
  .github/workflows/ci-dev-be.yml
  .github/workflows/deploy-prod-be.yml
  backend/.gitignore
  backend/Dockerfile
  backend/appspec.yml
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/scripts/deploy.sh
  backend/settings.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/main/java/codesquad/airbnb/AirbnbApplication.java
  backend/src/main/java/codesquad/airbnb/accomodation/AccommodationController.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Accommodation.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Address.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Image.java
  backend/src/main/java/codesquad/airbnb/accomodation/domain/Provides.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCount.java
  backend/src/main/java/codesquad/airbnb/accomodation/dto/PriceAndCountStatistics.java
  backend/src/main/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepository.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsService.java
  backend/src/main/java/codesquad/airbnb/accomodation/service/AmountUnitPolicy.java
  backend/src/main/java/codesquad/airbnb/config/JasyptConfig.java
  backend/src/main/java/codesquad/airbnb/config/QueryDSLConfig.java
  backend/src/main/java/codesquad/airbnb/exception/AirbnbRuntimeException.java
  backend/src/main/java/codesquad/airbnb/exception/ErrorResponse.java
  backend/src/main/java/codesquad/airbnb/exception/GlobalExceptionHandler.java
  backend/src/main/java/codesquad/airbnb/member/Member.java
  backend/src/main/java/codesquad/airbnb/reservation/Reservation.java
  backend/src/main/java/codesquad/airbnb/reservation/Schedule.java
  backend/src/main/java/codesquad/airbnb/reservation/StartEndDate.java
  backend/src/main/java/codesquad/airbnb/wish/Wish.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/sql/airbnb-schema.sql
  backend/src/test/java/codesquad/airbnb/AirbnbApplicationTests.java
  backend/src/test/java/codesquad/airbnb/ApiDocumentUtils.java
  backend/src/test/java/codesquad/airbnb/accomodation/AccommodationControllerTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/repository/AccommodationQueryRepositoryTest.java
  backend/src/test/java/codesquad/airbnb/accomodation/service/AccommodationStatisticsServiceTest.java
  backend/src/test/java/codesquad/airbnb/config/JasyptConfigTest.java
  backend/src/test/resources/application.properties
  backend/src/test/resources/sql/accommodation-statistics.sql
Labels: BE
